/* The person's own record: every mandate, newest first. Same content type as
   the Record block on the landing page — a mandate is a year, a line and the
   colleagues who were on it. The preamble is the two sentences the mandate
   page itself opens with; here it is folded away under the line and comes out
   on hover, because forty titles have to stay scannable.

   Fictional clients, as everywhere in this system. */
(() => {
  const M = (year, title, preamble, areas, sector, team) =>
    ({ year, title, preamble, areas, sector, team });

  window.VingePersonMandates = [
    M(2026, 'Biträdde Nordika vid försvaret mot Avenyrs offentliga uppköpsbud om 4,1 miljarder kronor',
      'Budet lades utan förvarning en fredagseftermiddag i februari. Styrelsen hade fjorton dagar på sig att svara, och gjorde det med en rekommendation att avvisa.',
      ['Publik M&A', 'Bolagsrätt'], 'Detaljhandel', ['Anders Kihlström', 'Petra Lindqvist']),
    M(2026, 'Företrädde Bergslagen Kraft i skiljeförfarande om prisjustering i ett tjugoårigt kraftavtal',
      'Motparten begärde omförhandling när elpriset föll under avtalets golv. Förfarandet avgjordes vid SCC efter arton månader.',
      ['Skiljeförfaranden', 'Energirätt'], 'Energi', ['Eva Fredrikson', 'Anders Kihlström']),
    M(2026, 'Rådgivare till Cendra Pharma vid förvärvet av en klinisk portfölj ur Ranstad Klinikers verksamhet',
      'Fyra pågående prövningar följde med i affären, var och en med sitt eget regulatoriska godkännande. Överlåtelsen delades därför upp i tre steg.',
      ['M&A', 'Life science-regulatoriskt'], 'Life science', ['Petra Lindqvist', 'Klara Sundin']),
    M(2025, 'Biträdde Serafim Invest vid förvärvet av Fältström Industri och den efterföljande refinansieringen',
      'Bolaget köptes ur en familjeägd struktur med fyra grenar som inte var överens. Finansieringen restes parallellt med förhandlingen.',
      ['Private equity', 'Bank och finans'], 'Industri', ['Anders Kihlström', 'Måns Ahlgren', 'Petra Lindqvist']),
    M(2025, 'Företrädde Norrsken Life Science vid noteringen på Nasdaq Stockholms huvudlista',
      'Bolaget hade två läkemedelskandidater och ingen intäkt. Prospektet fick därför bära hela argumentet.',
      ['Kapitalmarknad', 'Bolagsrätt'], 'Life science', ['Klara Sundin', 'Ingrid Törnqvist']),
    M(2025, 'Rådgivare till Karlavik Hamn vid Konkurrensverkets granskning av terminalavtalen',
      'Granskningen inleddes efter en anmälan från en konkurrerande operatör. Den avslutades utan åtgärd sjutton månader senare.',
      ['Konkurrensrätt', 'Regulatoriskt'], 'Transport', ['Eva Fredrikson', 'Anders Kihlström']),
    M(2025, 'Biträdde Vidarö Fastigheter vid avyttringen av samhällsfastighetsportföljen till en internationell köpare',
      'Fyrtioen fastigheter med kommunala hyresgäster och lika många hyresavtal att gå igenom. Affären stängdes på elva veckor.',
      ['Fastighetsrätt', 'M&A'], 'Fastigheter', ['Måns Ahlgren', 'Petra Lindqvist']),
    M(2024, 'Företrädde Nordika när Avenyr lade ett kontant bud på hela aktiestocken',
      'Det första av två bud från samma budgivare. Detta drogs tillbaka innan acceptfristen gick ut.',
      ['Publik M&A'], 'Detaljhandel', ['Anders Kihlström', 'Petra Lindqvist', 'Rikard Boström']),
    M(2024, 'Rådgivare till Aptera Medical vid konkurrensanmälan av förvärvet av Halvfors medicintekniska division',
      'Anmälan gick till fas två i två jurisdiktioner. Affären godkändes mot åtaganden om avyttring av en produktlinje.',
      ['Konkurrensrätt', 'M&A'], 'Life science', ['Eva Fredrikson', 'Klara Sundin']),
    M(2024, 'Biträdde Terrafors vid etableringen av ett samägt bolag för havsbaserad vindkraft',
      'Två parter med olika tidshorisonter och samma kapitalbehov. Aktieägaravtalet reglerar vad som händer när den ena vill ut.',
      ['Bolagsrätt', 'Energirätt'], 'Energi', ['Ingrid Törnqvist', 'Måns Ahlgren']),
    M(2024, 'Företrädde Stavgren Bank i tvist om ansvar för rådgivning vid strukturerade produkter',
      'Kärandena var fyrtio privatpersoner som drev talan gemensamt. Målet förlikades efter huvudförhandlingens andra vecka.',
      ['Tvistlösning', 'Regulatoriskt'], 'Bank och finans', ['Rikard Boström', 'Anders Kihlström']),
    M(2024, 'Rådgivare till Ostkant Logistik vid carve-out och försäljning av den nordiska åkeriverksamheten',
      'Verksamheten låg i sex bolag i tre länder och delade allt utom kunder. Separationen tog nio månader innan den kunde säljas.',
      ['M&A', 'Arbetsrätt'], 'Transport', ['Petra Lindqvist', 'Måns Ahlgren']),
    M(2023, 'Biträdde Blixtvik Telekom vid refinansieringen av kreditfaciliteten om 6,2 miljarder kronor',
      'Sju banker i syndikatet och ett bolag som just förlorat sitt största avtal. Villkoren skrevs om innan förfallodagen.',
      ['Bank och finans'], 'Telekom', ['Måns Ahlgren', 'Anders Kihlström']),
    M(2023, 'Företrädde Almnäs Bruk vid Mark- och miljödomstolens prövning av det utvidgade tillståndet',
      'Ansökan hade legat i fyra år när prövningen inleddes. Tillståndet meddelades med skärpta villkor för utsläpp till vatten.',
      ['Miljörätt', 'Regulatoriskt'], 'Skog och råvaror', ['Ingrid Törnqvist']),
    M(2023, 'Rådgivare till Norrmalm Kapital vid förvärvet av en minoritetspost i Ambion Software',
      'Posten kom med en styrelseplats och en option att köpa resten. Optionens utlösande villkor var hela förhandlingen.',
      ['M&A', 'Bolagsrätt'], 'Teknik', ['Petra Lindqvist', 'Klara Sundin']),
    M(2023, 'Biträdde Sköldkroken vid upphandlingen av entreprenaden för Tunnelbolaget Östs etapp tre',
      'Tilldelningen överprövades av två av de förlorande anbudsgivarna. Båda ansökningarna avslogs.',
      ['Offentlig upphandling', 'Tvistlösning'], 'Bygg och infrastruktur', ['Eva Fredrikson', 'Rikard Boström']),
    M(2022, 'Företrädde Klarsjö Försäkring vid Finansinspektionens tillsyn av försäkringsdistributionen',
      'Tillsynen rörde ersättningsmodellen till förmedlarna. Den avslutades med en anmärkning och ingen sanktionsavgift.',
      ['Regulatoriskt', 'Compliance'], 'Försäkring', ['Rikard Boström', 'Klara Sundin']),
    M(2022, 'Rådgivare till Hedmark Gruvor vid försäljningen av koncessionerna i Norrbotten',
      'Tre koncessioner, två av dem överklagade. Köpeskillingen delades i en fast del och en som föll ut vid lagakraftvunnet beslut.',
      ['M&A', 'Miljörätt'], 'Skog och råvaror', ['Ingrid Törnqvist', 'Måns Ahlgren']),
    M(2022, 'Biträdde Vartex Retail vid rekonstruktionen och den efterföljande ackordsuppgörelsen',
      'Bolaget hade 340 butiker och likviditet till sex veckor. Ackordet antogs av borgenärerna i november.',
      ['Obestånd och rekonstruktion'], 'Detaljhandel', ['Anders Kihlström', 'Rikard Boström']),
    M(2022, 'Företrädde Sundfast i tvist mot totalentreprenören om fel i tolv bostadsprojekt',
      'Felen var desamma i samtliga projekt och bestreds i samtliga. Målet avgjordes till kärandens fördel i hovrätten.',
      ['Tvistlösning', 'Fastighetsrätt'], 'Fastigheter', ['Rikard Boström']),
    M(2021, 'Rådgivare till Solvarv vid det gränsöverskridande samgåendet med en tysk solkraftsutvecklare',
      'Två bolag av jämförbar storlek och ingen självklar övertagare. Strukturen avgjordes av var noteringen skulle ligga.',
      ['M&A', 'Bolagsrätt'], 'Energi', ['Petra Lindqvist', 'Ingrid Törnqvist', 'Anders Kihlström']),
    M(2021, 'Biträdde Kvarnbo Mejeri vid förvärvet av en konkurrents produktionsanläggning i Skåne',
      'Anläggningen var den enda i sitt slag söder om Mälardalen. Konkurrensverket prövade affären i fas ett.',
      ['Konkurrensrätt', 'M&A'], 'Detaljhandel', ['Eva Fredrikson']),
    M(2021, 'Företrädde Tredje Vågen Media i förhandlingen om kollektivavtal vid övergången av verksamhet',
      'Etthundrasextio anställda gick över till en ny arbetsgivare. Förhandlingen fördes med tre fackliga organisationer parallellt.',
      ['Arbetsrätt'], 'Media', ['Klara Sundin']),
    M(2020, 'Rådgivare till Nyfors Elnät vid försäljningen av regionnätet till ett infrastrukturfondkonsortium',
      'Regleringen av intäktsramen bestämde priset mer än tillgången gjorde. Affären villkorades av Energimarknadsinspektionens godkännande.',
      ['M&A', 'Energirätt'], 'Energi', ['Måns Ahlgren', 'Ingrid Törnqvist']),
    M(2020, 'Biträdde Alveus Data vid dataskyddsgranskningen av molnplattformen för nordiska kunder',
      'Granskningen inleddes efter en incidentanmälan. Den ledde till ändrade avtalsvillkor mot samtliga underbiträden.',
      ['Dataskydd', 'IT och teknologi'], 'Teknik', ['Klara Sundin', 'Rikard Boström']),
    M(2019, 'Företrädde Vinterhamn Rederi i skiljeförfarande om leveransförsening av två fartyg',
      'Varvet var kinesiskt och avtalet engelskrättsligt. Förfarandet fördes i London och avgjordes efter två år.',
      ['Skiljeförfaranden'], 'Transport', ['Eva Fredrikson', 'Anders Kihlström']),
    M(2019, 'Rådgivare till Rosenhill Vård vid överlåtelsen av åtta äldreboenden till kommunal regi',
      'Verksamhetsövergången skulle ske vid ett och samma årsskifte. Personal, lokaler och journalsystem följde med.',
      ['Offentlig upphandling', 'Arbetsrätt'], 'Offentlig sektor', ['Ingrid Törnqvist', 'Klara Sundin']),
    M(2018, 'Biträdde Frostvik Kyl vid det första förvärvet i den europeiska expansionen',
      'Målbolaget låg i Nederländerna och hade två ägare med olika uppfattning om priset. Affären stängdes efter fjorton månader.',
      ['M&A', 'Skatt'], 'Industri', ['Petra Lindqvist', 'Måns Ahlgren']),
    M(2017, 'Företrädde Lindhem Bygg i entreprenadtvist om ansvaret för grundläggningen',
      'Sättningarna upptäcktes tre år efter slutbesiktning. Frågan var när preskriptionstiden hade börjat löpa.',
      ['Tvistlösning'], 'Bygg och infrastruktur', ['Rikard Boström']),
    M(2016, 'Rådgivare till Hägerlund Skog vid generationsskiftet och omstruktureringen av markinnehavet',
      'Innehavet hade legat i samma familj i fyra generationer och i fem bolag. Strukturen ritades om innan det gick vidare.',
      ['Bolagsrätt', 'Skatt'], 'Skog och råvaror', ['Måns Ahlgren']),
  ];
})();
